### ISSUE TITLE
phine/country

### ISSUE THREAD

**Issue by harikt** [dms-org/common.structure#1]
I noticed that this library is using phine/country package.

It looks like being abandoned. There are a few open PR's and issues related to that library. Is that a good thing that you guys can ask the maintainer and take that to dms ?

https://github.com/kherge-abandoned/lib-country

**Comment by TimeToogo** [comment]
We have replaced the dependency of `phine/country` in favor of `league/iso3166`.

Thanks for submitting this issue.
